#DROP DATABASE JUEGODB;
CREATE DATABASE JUEGODB;
USE JUEGODB;

CREATE TABLE JUGADOR(
  ID_JUGADOR INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(50) NOT NULL,
  PASS VARCHAR(50) NOT NULL,
  CONSTRAINT userID PRIMARY KEY(ID_JUGADOR),
  CONSTRAINT userName UNIQUE (USERNAME)
);

CREATE TABLE PARTIDA(
  ID_PARTIDA INT NOT NULL AUTO_INCREMENT,
  ID_JUGADORA INT NOT NULL,
  ID_JUGADORB INT NOT NULL,
  PUNTAJE INT NOT NULL,
  FINALIZADA INT NOT NULL,
  CONSTRAINT partidaID PRIMARY KEY(ID_PARTIDA),
  CONSTRAINT userAID FOREIGN KEY(ID_JUGADORA) REFERENCES JUGADOR(ID_JUGADOR),
  CONSTRAINT userBID FOREIGN KEY(ID_JUGADORB) REFERENCES JUGADOR(ID_JUGADOR)
);


CREATE TABLE RONDA(
  ID_RONDA INT NOT NULL AUTO_INCREMENT,
  ID_PARTIDA INT NOT NULL,
  RONDA INT NOT NULL,
  TURNO_ACT INT NOT NULL,
  CONSTRAINT rondaID PRIMARY KEY(ID_RONDA),
  CONSTRAINT rondaPartID UNIQUE(ID_RONDA, ID_PARTIDA, RONDA),
  CONSTRAINT partidID FOREIGN KEY(ID_PARTIDA) REFERENCES PARTIDA(ID_PARTIDA)
);

CREATE TABLE PREGUNTA(
  ID_PREGUNTA INT NOT NULL AUTO_INCREMENT,
  TEXTO VARCHAR(200) NOT NULL,
  RESP1 VARCHAR(200) NOT NULL,
  RESP2 VARCHAR(200) NOT NULL,
  RESP3 VARCHAR(200),
  CONSTRAINT preguntaID PRIMARY KEY(ID_PREGUNTA)
);


CREATE TABLE RESPUESTA(
  ID_RESPUESTA INT NOT NULL AUTO_INCREMENT,
  ID_PARTIDA INT NOT NULL,
  ID_RONDA  INT NOT NULL,
  ID_PREGUNTA INT NOT NULL,
  JUGADORA_RESP INT,
  JUGADORB_RESP INT,
  CONSTRAINT respuestaID PRIMARY KEY(ID_RESPUESTA),
  CONSTRAINT respuestaRP UNIQUE(ID_PARTIDA ,ID_RONDA ,ID_PREGUNTA ),
  CONSTRAINT respPartID FOREIGN KEY(ID_PARTIDA) REFERENCES PARTIDA(ID_PARTIDA),
  CONSTRAINT respRondID FOREIGN KEY(ID_RONDA) REFERENCES RONDA(ID_RONDA),
  CONSTRAINT respPreID FOREIGN KEY(ID_PREGUNTA) REFERENCES PREGUNTA(ID_PREGUNTA)
);





